# Application properties that need to be
# embedded within the web application can be included here
cas:
  monitor:
    endpoints:
      endpoint:
        oauthTokens:
          access: PERMIT
  service-registry:
    core:
      init-from-json: true
    json:
      location: classpath:/services
management:
  endpoint:
    oauthTokens:
      enabled: true
  endpoints:
    web:
      exposure:
        include: oauthTokens
